# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Upload Python Package

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout 📦
      uses: actions/checkout@v4
    - name: Setup PDM 📦
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build package 👷‍♂️
      run: pdm build -v --no-sdist
    - name: Upload wheels 👷‍♂️
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      id-token: write
    steps:
      - name: Download wheels 👷‍♂️
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist
      - name: Publish to PyPi 🚀
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          packages-dir: dist
          verbose: true

  release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      id-token: write
    steps:
      - name: Checkout 📦
        uses: actions/checkout@v4
      - name: Download wheels 👷‍♂️
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist
      - name: Publish GitHub Release 📝
        uses: softprops/action-gh-release@v2
        with:
          name: dns-manager ${{github.ref_name}}
          files: |
            dist/*.whl
