# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Upload Python Package

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
jobs:
  deploy:
    strategy:
      matrix:
        python-version: [3.12]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Publish package distributions to PyPI
      run: pdm publish
