name: Generate Release Tag

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout 📦
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Python Semantic Release 🚀
        id: release
        uses: python-semantic-release/python-semantic-release@v10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: true
          config_file: releaserc.toml
          verbosity: 2
      - name: Install the latest version of uv 📦
        uses: astral-sh/setup-uv@v6
      - name: Install Python 📦
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build distributions 📦
        run: uv build --wheel
      - name: Publish package distributions to GitHub Releases 🚀
        if: steps.release.outputs.released == 'true'
        uses: python-semantic-release/publish-action@v10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
      - name: Publish package distributions to PyPI 🚀
        if: steps.release.outputs.released == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
    outputs:
      released: ${{ steps.release.outputs.released }}
      tag: ${{ steps.release.outputs.tag }}
